# Generated by Django 2.1.7 on 2019-03-29 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0004_auto_20190329_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='secr_announcement',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
