# Generated by Django 2.1.7 on 2019-03-29 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0005_auto_20190329_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='secr_announcement',
            options={'ordering': ['-date']},
        ),
    ]
