# Generated by Django 2.1.7 on 2019-03-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0009_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lname',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='First', help_text='First Name', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='Last', help_text='Last Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grammateia',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Grammateia',
        ),
    ]
