# Generated by Django 2.1.7 on 2019-03-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0010_auto_20190329_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_secretary.Professor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_secretary.Student'),
        ),
    ]
