# Generated by Django 2.1.7 on 2019-03-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0013_auto_20190330_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='didaskalia',
            field=models.ManyToManyField(null=True, to='e_secretary.Didaskalia'),
        ),
    ]
