# Generated by Django 2.1.7 on 2019-03-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0014_auto_20190330_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='didaskalia',
            field=models.ManyToManyField(blank=True, null=True, to='e_secretary.Didaskalia'),
        ),
    ]
