# Generated by Django 2.1.7 on 2019-04-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0017_auto_20190330_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='photo',
        ),
    ]
