# Generated by Django 2.1.7 on 2019-04-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0019_didaskalia_perigrafi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orologio',
            name='time',
            field=models.DurationField(),
        ),
    ]
