# Generated by Django 2.1.7 on 2019-04-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0021_auto_20190402_1323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='didaskalia',
            old_name='course_id',
            new_name='course',
        ),
    ]
