# Generated by Django 2.1.7 on 2019-04-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0023_auto_20190402_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dilosi',
            old_name='didaskalies',
            new_name='didaskalia',
        ),
    ]
