# Generated by Django 2.1.7 on 2019-04-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0024_auto_20190402_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drastiriotita',
            old_name='date',
            new_name='due_date',
        ),
    ]
