# Generated by Django 2.1.7 on 2019-04-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0028_auto_20190402_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='simmetoxidrastiriotita',
            name='title',
            field=models.CharField(default='Test', max_length=45),
            preserve_default=False,
        ),
    ]
