# Generated by Django 2.1.7 on 2019-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0032_auto_20190403_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='programma_spoudwn',
            field=models.CharField(choices=[('HMTY_Bachelor', 'HMTY_Bachelor'), ('HMTY_Masters', 'HMTY_Masters')], max_length=20),
        ),
    ]
