# Generated by Django 2.1.7 on 2019-04-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0033_auto_20190403_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('HMTY', 'HMTY'), ('HMTY', 'HMTY')], max_length=20),
        ),
    ]
