# Generated by Django 2.1.7 on 2019-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0036_auto_20190403_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fathername',
        ),
        migrations.AddField(
            model_name='profile',
            name='fathername',
            field=models.CharField(default='Mpampakas', max_length=20),
            preserve_default=False,
        ),
    ]
