# Generated by Django 2.1.7 on 2019-04-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0037_auto_20190403_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='drastiriotita',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='drastiriotita',
            name='perigrafi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
