# Generated by Django 2.1.7 on 2019-04-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0038_auto_20190403_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drastiriotita',
            name='didaskalia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_secretary.Didaskalia'),
        ),
    ]
