# Generated by Django 2.1.7 on 2019-04-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0040_auto_20190404_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='didaskalia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_secretary.Didaskalia'),
        ),
    ]
