# Generated by Django 2.2 on 2019-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0042_auto_20190502_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='didaskalia',
            field=models.ManyToManyField(blank=True, to='e_secretary.Didaskalia'),
        ),
    ]
