# Generated by Django 2.2 on 2019-05-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0043_auto_20190502_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('ENERGOS', 'ENERGOS'), ('ARMY', 'ARMY'), ('GRADES', 'GRADES')], max_length=50),
        ),
    ]
