# Generated by Django 2.2 on 2019-05-06 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0044_auto_20190506_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_requested',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
