# Generated by Django 2.2 on 2019-05-06 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0045_auto_20190506_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='copies',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
