# Generated by Django 2.2 on 2019-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0047_auto_20190506_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
