# Generated by Django 2.2 on 2019-05-06 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0048_auto_20190506_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_requested',
            field=models.DateField(default=datetime.datetime(2019, 5, 6, 17, 26, 20, 333804)),
        ),
    ]
