# Generated by Django 2.2 on 2019-05-06 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0049_auto_20190506_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_requested',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
