# Generated by Django 2.2 on 2019-05-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_secretary', '0050_auto_20190506_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('ENERGOS', 'ENERGOS'), ('ARMY', 'ARMY'), ('GRADES', 'GRADES')], max_length=10),
        ),
    ]
